version: '3'

services:

  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - ./db-data/postgresql/:/var/lib/postgresql/data/