migrate_down:
	migrate -database postgres://postgres:postgres@localhost:5432/test?sslmode=disable -path ../db/migrations down

migrate_up:
	migrate -database postgres://postgres:postgres@localhost:5432/test?sslmode=disable -path ../db/migrations up